name: DB Backup
on:
  push:
    branches: [ master ]
  workflow_dispatch: {}
  schedule:
      # nightly @ midnight
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        with:
          version: 'v3.5.0'

      - name: glcloud install
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID:  ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run a one-line script
        run: |
          sops exec-env secrets/prod.env 'bash scripts/backup_mongo.sh'
