name: DB Backup
on:
  push:
    branches: [ db-backup ]
  workflow_dispatch: {}
  schedule:
      # nightly @ midnight
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        with:
          version: 'v3.5.0'
      - name: Backup mongo db
        run: |
          sops -d secrets/service-account.json > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json
          gcloud config set project "${{ secrets.PROJECT_ID }}"
          make backup
